import type { Operator } from "@/data/operators";
import { Button } from "@/components/ui/button";
import { BadgeCheck, ExternalLink, Mail, MapPin, Phone, Star } from "lucide-react";

type OperatorCardProps = { operator: Operator; reviewCount: number; onReview: () => void };

export function OperatorCard({ operator, reviewCount, onReview }: OperatorCardProps) {
  const totalReviews = operator.reviews + reviewCount;
  const subject = encodeURIComponent(`Tour enquiry for ${operator.name}`);
  const body = encodeURIComponent(`Hello ${operator.name},\n\nI would like help planning a Kanyakumari tour. Please share your availability and package options.\n\nThank you.`);
  const logo = operator.logo || (operator.website ? `https://www.google.com/s2/favicons?domain=${new URL(operator.website).hostname}&sz=128` : "");
  const mapLink = operator.mapLink || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(operator.name)}`;
  return <article className="group overflow-hidden rounded-2xl border border-border bg-card shadow-soft transition-all duration-300 hover:shadow-xl"><div className="grid sm:grid-cols-[40%_1fr]"><div className="relative aspect-[4/3] overflow-hidden bg-muted sm:aspect-auto"><img src={logo} alt={`${operator.name} logo`} loading="lazy" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" />{operator.featured && <span className="absolute left-3 top-3 rounded-full bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground">Featured</span>}</div><div className="flex flex-col p-6"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-secondary/10 px-2 py-0.5 font-medium text-secondary">{operator.type}</span>{operator.verified && <span className="inline-flex items-center gap-1 text-secondary"><BadgeCheck className="h-3.5 w-3.5" />Verified</span>}</div><h2 className="mt-2 font-display text-xl font-semibold">{operator.name}</h2><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{operator.location || "Kanyakumari district"}</p><p className="mt-3 line-clamp-2 text-sm text-muted-foreground">{operator.speciality}</p><div className="mt-4 flex items-center gap-1 text-xs text-muted-foreground"><Star className="h-3.5 w-3.5 fill-accent text-accent" /><span>{operator.rating.toFixed(1)} &bull; {totalReviews.toLocaleString()} reviews</span></div><div className="mt-5 border-t border-border pt-4"><div className="flex flex-wrap items-center gap-2"><Button asChild variant="outline" size="sm"><a href={`tel:${operator.phone.replace(/[^+\d]/g, "")}`}><Phone className="mr-1 h-4 w-4" />Call</a></Button><Button asChild variant="outline" size="sm"><a href={`mailto:${operator.email}`}><Mail className="mr-1 h-4 w-4" />Email</a></Button><Button asChild variant="outline" size="sm"><a href={mapLink} target="_blank" rel="noreferrer"><MapPin className="mr-1 h-4 w-4" />Maps</a></Button>{operator.website && <Button asChild variant="outline" size="sm"><a href={operator.website} target="_blank" rel="noreferrer"><ExternalLink className="mr-1 h-4 w-4" />Website</a></Button>}<Button variant="outline" size="sm" onClick={onReview}>Review</Button><Button asChild variant="hero" size="sm"><a href={`mailto:${operator.email}?subject=${subject}&body=${body}`}><Mail className="mr-1 h-4 w-4" />Enquire</a></Button></div></div></div></div></article>;
}
